name: CI-Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify project
        run: mvn clean verify

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Dependency Check
        run: mvn org.owasp:dependency-check-maven:check