name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-test:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Lệnh verify sẽ tự động chạy cả compile, test, jacoco report và đóng gói
      - name: Run Maven Verify
        run: mvn clean verify

      - name: Phân tích báo cáo và Comment vào PR
        if: github.event_name == 'pull_request'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0 # vì legacy code chưa test gì cả
          min-coverage-changed-files: 80
          title: 📊 Báo cáo Kiểm thử JaCoCo
          update-comment: true

  dependency-check:
    name: OWASP Dependency Security Check
    runs-on: ubuntu-latest
    # Cài đặt để job bảo mật này chạy song song với job Build ở trên
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache NVD database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-${{ runner.os }}-${{ steps.date.outputs.date }}
          restore-keys: |
            nvd-${{ runner.os }}-

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}